### ISSUE TITLE
Missing local hostname

### ISSUE THREAD

**Issue by haleakala269** [example42/puppet-hosts#6]
Hello,

we're using example42/hosts puppet module to manage the /etc/hosts file of our Linux (CentOS) cluster hosts.

But, for unknown reason, /etc/hosts file does not contain the local entry host.

For example : 
- on host_a VM, no host_a entry in /etc/hosts
- on host_b VM, no host_b entry in /etc/hosts
- etc.

Each /etc/hosts file contains all other cluster nodes.

Any idea ?

Thanks in advance.

Regards.

**Comment by alvagante** [comment]
Are you using the parameter   dynamic_mode     => true ?
Is so, the host entry for the local node should appear on that node at a second puppet run, that due to how exported resources (needed for dynamic mode) work.
If not, please give me more details on the parameters you use with this class.

**Comment by haleakala269** [comment]
Hi,

Thanks for your support.

Yes, we’re using the dynamic mode :

  class { 'hosts':
      dynamic_mode      => true,
      dynamic_magicvar  => 'customer_id',
  }

customer_id is a custom fact. Its value is correct on each node (in the example below : esabc27i).

hosts puppet module release is 2.0.17 (example42-hosts (v2.0.17))

Even if we force the puppet agent (several times), the local hostname is not added to /etc/hosts file.

When we purge /etc/hosts file and we for puppet agent, all cluster nodes are added except the local node ☹

Example of /etc/hosts file :

[root@esabc27i-vcs001 ~]# cat /etc/hosts
# HEADER: This file was autogenerated at Wed Nov 04 15:03:47 +0000 2015
# HEADER: by puppet.  While it can still be managed manually, it
# HEADER: is definitely not recommended.
127.0.0.1       localhost       localhost.localdomain localhost4 localhost4.localdomain4
::1     localhost       localhost.localdomain localhost6 localhost6.localdomain6
10.100.108.4    esabc27i-ves002.novalocal       esabc27i-ves002
10.100.108.7    esabc27i-vhs001.novalocal       esabc27i-vhs001
10.100.108.6    esabc27i-vhm002.novalocal       esabc27i-vhm002
10.100.108.3    esabc27i-ves001.novalocal       esabc27i-ves001
10.100.108.5    esabc27i-vhm001.novalocal       esabc27i-vhm001

So, missing esabc27i-vcs001 entry.

Regards.

**Comment by haleakala269** [comment]
Hello,

problem solved :-)
It was due to puppet packages releases :
- before :
puppetdb-terminus-2.2.2-1.el6.noarch
puppet-3.7.3-1.el6.noarch
puppetserver-1.0.0-1.el6.noarch
puppetdb-2.2.2-1.el6.noarch

- After :
puppetdb-terminus-2.3.8-1.el6.noarch
puppet-3.8.4-1.el6.noarch
puppetdb-2.3.8-1.el6.noarch
puppetserver-1.1.2-1.el6.noarch

Regards.

**Comment by alvagante** [comment]
Thanks for the update. Still I wonder why it didn't work before... Closing the issue
